"""Role and permission definitions for KRX admin security."""

from __future__ import annotations

from typing import Iterable

# All admin roles (code -> display name)
ADMIN_ROLE_DEFINITIONS: dict[str, str] = {
    "owner": "オーナー",
    "admin": "管理者",
    "sales_manager": "販売マネージャー",
    "buyback_manager": "買取マネージャー",
    "appraiser": "査定担当",
    "identity_verifier": "本人確認担当",
    "inventory_manager": "在庫マネージャー",
    "shipping_manager": "発送マネージャー",
    "payment_manager": "決済マネージャー",
    "support_manager": "サポートマネージャー",
    "live_moderator": "ライブモデレーター",
    "viewer": "閲覧専用",
}

# Permission codes used by admin security APIs and future modules.
ADMIN_PERMISSION_DEFINITIONS: list[tuple[str, str, str]] = [
    ("admin.users.read", "管理者一覧閲覧", "security"),
    ("admin.users.write", "管理者追加・編集", "security"),
    ("admin.roles.read", "役割閲覧", "security"),
    ("admin.roles.write", "役割・権限変更", "security"),
    ("admin.audit.read", "監査ログ閲覧", "security"),
    ("admin.settings.write", "重要設定変更", "settings"),
    ("admin.email.read", "メールテンプレート閲覧", "settings"),
    ("admin.email.write", "メールテンプレート編集", "settings"),
    ("admin.pii.read", "個人情報閲覧", "privacy"),
    ("admin.csv.export", "CSV出力", "export"),
    ("admin.reauth", "再認証", "security"),
    ("buyback.request.read", "買取申請閲覧", "buyback"),
    ("buyback.assessment.write", "買取査定変更", "buyback"),
    ("buyback.request.status.write", "買取申請状態変更", "buyback"),
    ("buyback.identity.read", "買取本人確認閲覧", "buyback"),
    ("buyback.identity.write", "買取本人確認審査", "buyback"),
    ("buyback.payout.complete", "買取振込完了", "buyback"),
    ("buyback.catalog.import", "買取カタログ取込", "buyback"),
    ("buyback.catalog.read", "買取カタログ閲覧", "buyback"),
    ("buyback.catalog.write", "買取カタログ変更", "buyback"),
    ("buyback.receive", "買取荷物受付", "buyback"),
    ("buyback.package.read", "梱包情報閲覧", "buyback"),
    ("buyback.package.write", "梱包作成・完了", "buyback"),
    ("buyback.ship.read", "発送先閲覧", "buyback"),
    ("buyback.ship.pii.read", "発送先個人情報閲覧", "buyback"),
    ("buyback.ship.confirm", "発送確定", "buyback"),
    ("buyback.print.internal", "内部ラベル印刷", "buyback"),
    ("buyback.print.pii", "住所付き印刷", "buyback"),
    ("buyback.logs.read", "買取物流ログ閲覧", "buyback"),
    ("buyback.settings.read", "買取チャネル設定閲覧", "buyback"),
    ("buyback.settings.write", "買取チャネル設定変更", "buyback"),
    ("buyback.reservation.read", "店舗買取予約閲覧", "buyback"),
    ("kyc.view", "本人確認一覧閲覧", "buyback_kyc"),
    ("kyc.review", "本人確認審査", "buyback_kyc"),
    ("kyc.document.view", "本人確認書類閲覧", "buyback_kyc"),
    ("kyc.document.print", "本人確認記録印刷", "buyback_kyc"),
    ("guardian_consent.view", "保護者同意閲覧", "buyback_kyc"),
    ("payout.view", "振込一覧閲覧", "buyback_payout"),
    ("payout.bank_account.view", "振込口座詳細閲覧", "buyback_payout"),
    ("payout.execute", "振込実行", "buyback_payout"),
    ("payout.complete", "振込完了記録", "buyback_payout"),
    ("antique_ledger.view", "古物台帳閲覧", "buyback_compliance"),
    ("antique_ledger.print", "古物台帳印刷", "buyback_compliance"),
    ("audit_log.view", "買取監査ログ閲覧", "buyback_audit"),
    ("live.read", "ライブ配信閲覧", "live"),
    ("live.write", "ライブ配信管理", "live"),
    ("live.moderate", "ライブコメントモデレート", "live"),
    ("auction.read", "Live auction read", "live"),
    ("auction.write", "Live auction write", "live"),
    ("auction.bid", "Live auction bid", "live"),
    ("auction.manage", "Live auction manage", "live"),
    ("offer.read", "Live offer read", "live"),
    ("offer.create", "Live offer create", "live"),
    ("offer.review", "Live offer review", "live"),
    ("offer.manage", "Live offer manage", "live"),
    ("point.read", "ポイント閲覧", "points"),
    ("point.grant", "ポイント手動付与", "points"),
    ("point.deduct", "ポイント手動減算", "points"),
    ("point.settings", "ポイント設定", "points"),
    ("point.audit", "ポイント監査ログ", "points"),
    ("live.broadcast", "ライブ配信操作", "live"),
]

ROLE_PERMISSION_CODES: dict[str, set[str]] = {
    "owner": {code for code, _, _ in ADMIN_PERMISSION_DEFINITIONS},
    "admin": {
        "auction.read",
        "auction.write",
        "auction.bid",
        "auction.manage",
        "offer.read",
        "offer.create",
        "offer.review",
        "offer.manage",
        "point.read",
        "point.grant",
        "point.deduct",
        "point.settings",
        "point.audit",
        "admin.users.read",
        "admin.users.write",
        "admin.roles.read",
        "admin.audit.read",
        "admin.settings.write",
        "admin.email.read",
        "admin.email.write",
        "admin.pii.read",
        "admin.csv.export",
        "admin.reauth",
        "buyback.request.read",
        "buyback.assessment.write",
        "buyback.request.status.write",
        "buyback.identity.read",
        "buyback.identity.write",
        "buyback.payout.complete",
        "buyback.catalog.import",
        "buyback.catalog.read",
        "buyback.catalog.write",
        "buyback.receive",
        "buyback.package.read",
        "buyback.package.write",
        "buyback.ship.read",
        "buyback.ship.pii.read",
        "buyback.ship.confirm",
        "buyback.print.internal",
        "buyback.print.pii",
        "buyback.logs.read",
        "buyback.settings.read",
        "buyback.settings.write",
        "buyback.reservation.read",
        "kyc.view",
        "kyc.review",
        "kyc.document.view",
        "kyc.document.print",
        "guardian_consent.view",
        "payout.view",
        "payout.bank_account.view",
        "payout.execute",
        "payout.complete",
        "antique_ledger.view",
        "antique_ledger.print",
        "audit_log.view",
        "live.read",
        "live.write",
        "live.moderate",
        "live.broadcast",
    },
    "sales_manager": {
        "auction.read",
        "auction.write",
        "auction.bid",
        "auction.manage",
        "offer.read",
        "offer.create",
        "offer.review",
        "offer.manage",
        "point.read",
        "admin.audit.read",
        "admin.csv.export",
        "admin.reauth",
        "live.read",
        "live.write",
        "live.moderate",
        "live.broadcast",
    },
    "buyback_manager": {
        "admin.audit.read",
        "admin.pii.read",
        "admin.csv.export",
        "admin.reauth",
        "buyback.request.read",
        "buyback.assessment.write",
        "buyback.request.status.write",
        "buyback.identity.read",
        "buyback.identity.write",
        "buyback.payout.complete",
        "buyback.catalog.import",
        "buyback.catalog.read",
        "buyback.catalog.write",
        "buyback.receive",
        "buyback.package.read",
        "buyback.package.write",
        "buyback.ship.read",
        "buyback.ship.pii.read",
        "buyback.ship.confirm",
        "buyback.print.internal",
        "buyback.print.pii",
        "buyback.logs.read",
        "buyback.settings.read",
        "buyback.settings.write",
        "buyback.reservation.read",
        "kyc.view",
        "kyc.review",
        "kyc.document.view",
        "kyc.document.print",
        "guardian_consent.view",
        "payout.view",
        "payout.bank_account.view",
        "payout.execute",
        "payout.complete",
        "antique_ledger.view",
        "antique_ledger.print",
        "audit_log.view",
    },
    "appraiser": {
        "admin.reauth",
        "buyback.request.read",
        "buyback.assessment.write",
    },
    "identity_verifier": {
        "admin.audit.read",
        "admin.reauth",
        "kyc.view",
        "kyc.review",
        "kyc.document.view",
        "kyc.document.print",
        "guardian_consent.view",
        "audit_log.view",
        "buyback.identity.read",
        "buyback.identity.write",
    },
    "inventory_manager": {
        "admin.audit.read",
        "admin.csv.export",
        "admin.reauth",
        "buyback.request.read",
        "buyback.receive",
        "buyback.package.read",
        "buyback.print.internal",
        "buyback.logs.read",
    },
    "shipping_manager": {
        "admin.audit.read",
        "admin.csv.export",
        "admin.reauth",
        "buyback.request.read",
        "buyback.package.read",
        "buyback.package.write",
        "buyback.ship.read",
        "buyback.ship.pii.read",
        "buyback.ship.confirm",
        "buyback.print.internal",
        "buyback.print.pii",
        "buyback.logs.read",
    },
    "payment_manager": {
        "admin.audit.read",
        "admin.reauth",
        "buyback.request.read",
        "payout.view",
        "payout.bank_account.view",
        "payout.execute",
        "payout.complete",
        "audit_log.view",
        "buyback.payout.complete",
    },
    "support_manager": {
        "auction.read",
        "auction.bid",
        "offer.read",
        "offer.create",
        "admin.audit.read",
        "admin.reauth",
        "buyback.request.read",
        "buyback.logs.read",
        "audit_log.view",
        "live.read",
        "live.moderate",
    },
    "live_moderator": {
        "auction.read",
        "auction.bid",
        "offer.read",
        "offer.create",
        "admin.reauth",
        "live.read",
        "live.moderate",
    },
    "viewer": {
        "admin.users.read",
        "admin.roles.read",
        "admin.audit.read",
        "buyback.request.read",
        "buyback.catalog.read",
        "buyback.logs.read",
    },
}

OWNER_ROLE_CODE = "owner"
VIEWER_ROLE_CODE = "viewer"

# Roles that cannot be assigned through normal admin UI/API (owner only via bootstrap).
PROTECTED_ASSIGNMENT_ROLES = {OWNER_ROLE_CODE}

MAX_FAILED_LOGIN_ATTEMPTS = 5
LOGIN_LOCKOUT_MINUTES = 30
REAUTH_VALID_MINUTES = 15


def permission_codes_for_role(role_code: str) -> set[str]:
    return set(ROLE_PERMISSION_CODES.get(role_code, set()))


def all_permission_codes() -> Iterable[str]:
    for code, _, _ in ADMIN_PERMISSION_DEFINITIONS:
        yield code
