# Pokemon name mapping (Japanese to English)
# This dictionary covers the first 151 Pokemon plus popular ones and newer generations.

POKEMON_NAME_MAP = {
    "フシギダネ": "Bulbasaur",
    "フシギソウ": "Ivysaur",
    "フシギバナ": "Venusaur",
    "ヒトカゲ": "Charmander",
    "リザード": "Charmeleon",
    "リザードン": "Charizard",
    "ゼニガメ": "Squirtle",
    "カメール": "Wartortle",
    "カメックス": "Blastoise",
    "キャタピー": "Caterpie",
    "トランセル": "Metapod",
    "バタフリー": "Butterfree",
    "ビードル": "Weedle",
    "コクーン": "Kakuna",
    "スピアー": "Beedrill",
    "ポッポ": "Pidgey",
    "ピジョン": "Pidgeotto",
    "ピジョット": "Pidgeot",
    "コラッタ": "Rattata",
    "ラッタ": "Raticate",
    "オニスズメ": "Spearow",
    "オニドリル": "Fearow",
    "アーボ": "Ekans",
    "アーボック": "Arbok",
    "ピカチュウ": "Pikachu",
    "ライチュウ": "Raichu",
    "サンド": "Sandshrew",
    "サンドパン": "Sandslash",
    "ニドラン♀": "Nidoran♀",
    "ニドリーナ": "Nidorina",
    "ニドクイン": "Nidoqueen",
    "ニドラン♂": "Nidoran♂",
    "ニドリーノ": "Nidorino",
    "ニドキング": "Nidoking",
    "ピッピ": "Clefairy",
    "ピクシー": "Clefable",
    "ロコン": "Vulpix",
    "キュウコン": "Ninetales",
    "プリン": "Jigglypuff",
    "プクリン": "Wigglytuff",
    "ズバット": "Zubat",
    "ゴルバット": "Golbat",
    "ナゾノクサ": "Oddish",
    "クサイハナ": "Gloom",
    "ラフレシア": "Vileplume",
    "パラス": "Paras",
    "パラセクト": "Parasect",
    "コンパン": "Venonat",
    "モルフォン": "Venomoth",
    "ディグダ": "Diglett",
    "ダグトリオ": "Dugtrio",
    "ニャース": "Meowth",
    "ペルシアン": "Persian",
    "コダック": "Psyduck",
    "ゴルダック": "Golduck",
    "マンキー": "Mankey",
    "オコリザル": "Primeape",
    "ガーディ": "Growlithe",
    "ウインディ": "Arcanine",
    "ニョロモ": "Poliwag",
    "ニョロゾ": "Poliwhirl",
    "ニョロボン": "Poliwrath",
    "ケーシィ": "Abra",
    "ユンゲラー": "Kadabra",
    "フーディン": "Alakazam",
    "ワンリキー": "Machop",
    "ゴーリキー": "Machoke",
    "カイリキー": "Machamp",
    "マダツボミ": "Bellsprout",
    "ウツドン": "Weepinbell",
    "ウツボット": "Victreebel",
    "メノクラゲ": "Tentacool",
    "ドククラゲ": "Tentacruel",
    "イシツブテ": "Geodude",
    "ゴローン": "Graveler",
    "ゴローニャ": "Golem",
    "ポニータ": "Ponyta",
    "ギャロップ": "Rapidash",
    "ヤドン": "Slowpoke",
    "ヤドラン": "Slowbro",
    "コイル": "Magnemite",
    "レアコイル": "Magneton",
    "カモネギ": "Farfetch'd",
    "ドードー": "Doduo",
    "ドードリオ": "Dodrio",
    "パウワウ": "Seel",
    "ジュゴン": "Dewgong",
    "ベトベター": "Grimer",
    "ベトベトン": "Muk",
    "シェルダー": "Shellder",
    "パルシェン": "Cloyster",
    "ゴース": "Gastly",
    "ゴースト": "Haunter",
    "ゲンガー": "Gengar",
    "イワーク": "Onix",
    "スリープ": "Drowzee",
    "スリーパー": "Hypno",
    "クラブ": "Krabby",
    "キングラー": "Kingler",
    "ビリリダマ": "Voltorb",
    "マルマイン": "Electrode",
    "タマタマ": "Exeggcute",
    "ナッシー": "Exeggutor",
    "カラカラ": "Cubone",
    "ガラガラ": "Marowak",
    "サワムラー": "Hitmonlee",
    "エビワラー": "Hitmonchan",
    "ベロリンガ": "Lickitung",
    "ドガース": "Koffing",
    "マタドガス": "Weezing",
    "サイホーン": "Rhyhorn",
    "サイドン": "Rhydon",
    "ラッキー": "Chansey",
    "モンジャラ": "Tangela",
    "ガルーラ": "Kangaskhan",
    "タッツー": "Horsea",
    "シードラ": "Seadra",
    "トサキント": "Goldeen",
    "アズマオウ": "Seaking",
    "ヒトデマン": "Staryu",
    "スターミー": "Starmie",
    "バリヤード": "Mr. Mime",
    "ストライク": "Scyther",
    "ルージュラ": "Jynx",
    "エレブー": "Electabuzz",
    "ブーバー": "Magmar",
    "カイロス": "Pinsir",
    "ケンタロス": "Tauros",
    "コイキング": "Magikarp",
    "ギャラドス": "Gyarados",
    "ラプラス": "Lapras",
    "メタモン": "Ditto",
    "イーブイ": "Eevee",
    "シャワーズ": "Vaporeon",
    "サンダース": "Jolteon",
    "ブースター": "Flareon",
    "ポリゴン": "Porygon",
    "オムナイト": "Omanyte",
    "オムスター": "Omastar",
    "カブト": "Kabuto",
    "カブトプス": "Kabutops",
    "プテラ": "Aerodactyl",
    "カビゴン": "Snorlax",
    "フリーザー": "Articuno",
    "サンダー": "Zapdos",
    "ファイヤー": "Moltres",
    "ミニリュウ": "Dratini",
    "ハクリュー": "Dragonair",
    "カイリュー": "Dragonite",
    "ミュウツー": "Mewtwo",
    "ミュウ": "Mew",
    # Generation 2
    "チコリータ": "Chikorita",
    "ベイリーフ": "Bayleef",
    "メガニウム": "Meganium",
    "ヒノアラシ": "Cyndaquil",
    "マグマラシ": "Quilava",
    "バクフーン": "Typhlosion",
    "ワニノコ": "Totodile",
    "アリゲイツ": "Croconaw",
    "オーダイル": "Feraligatr",
    "オタチ": "Sentret",
    "オオタチ": "Furret",
    "ホーホー": "Hoothoot",
    "ヨルノズク": "Noctowl",
    "レディバ": "Ledyba",
    "レディアン": "Ledian",
    "イトマル": "Spinarak",
    "アリアドス": "Ariados",
    "クロバット": "Crobat",
    "チョンチー": "Chinchou",
    "ランターン": "Lanturn",
    "ピチュー": "Pichu",
    "ピィ": "Cleffa",
    "ププリン": "Igglybuff",
    "トゲピー": "Togepi",
    "トゲチック": "Togetic",
    "ネイティ": "Natu",
    "ネイティオ": "Xatu",
    "メリープ": "Mareep",
    "モココ": "Flaaffy",
    "デンリュウ": "Ampharos",
    "キレイハナ": "Bellossom",
    "マリル": "Marill",
    "マリルリ": "Azumarill",
    "ウソッキー": "Sudowoodo",
    "ニョロトノ": "Politoed",
    "ハネッコ": "Hoppip",
    "ポポッコ": "Skiploom",
    "ワタッコ": "Jumpluff",
    "エイパム": "Aipom",
    "ヒマナッツ": "Sunkern",
    "キマワリ": "Sunflora",
    "ヤンヤンマ": "Yanma",
    "ウパー": "Wooper",
    "ヌオー": "Quagsire",
    "エーフィ": "Espeon",
    "ブラッキー": "Umbreon",
    "ヤミカラス": "Murkrow",
    "ヤドキング": "Slowking",
    "ムウマ": "Misdreavus",
    "アンノーン": "Unown",
    "ソーナンス": "Wobbuffet",
    "キリンリキ": "Girafarig",
    "クヌギダマ": "Pineco",
    "フォレトス": "Forretress",
    "ノコッチ": "Dunsparce",
    "グライガー": "Gligar",
    "ハガネール": "Steelix",
    "ブルー": "Snubbull",
    "グランブル": "Granbull",
    "ハリーセン": "Qwilfish",
    "ハッサム": "Scizor",
    "ツボツボ": "Shuckle",
    "ヘラクロス": "Heracross",
    "ニューラ": "Sneasel",
    "ヒメグマ": "Teddiursa",
    "リングマ": "Ursaring",
    "マグマッグ": "Slugma",
    "マグカルゴ": "Magcargo",
    "ウリムー": "Swinub",
    "イノムー": "Piloswine",
    "サニーゴ": "Corsola",
    "テッポウオ": "Remoraid",
    "オクタン": "Octillery",
    "デリバード": "Delibird",
    "マンタイン": "Mantine",
    "エアームド": "Skarmory",
    "デルビル": "Houndour",
    "ヘルガー": "Houndoom",
    "キングドラ": "Kingdra",
    "ゴマゾウ": "Phanpy",
    "ドンファン": "Donphan",
    "ポリゴン2": "Porygon2",
    "オドシシ": "Stantler",
    "ドーブル": "Smeargle",
    "バルキー": "Tyrogue",
    "カポエラー": "Hitmontop",
    "ムチュール": "Smoochum",
    "エレキッド": "Elekid",
    "ブビィ": "Magby",
    "ミルタンク": "Miltank",
    "ハピナス": "Blissey",
    "ライコウ": "Raikou",
    "エンテイ": "Entei",
    "スイクン": "Suicune",
    "ヨーギラス": "Larvitar",
    "サナギラス": "Pupitar",
    "バンギラス": "Tyranitar",
    "ルギア": "Lugia",
    "ホウオウ": "Ho-Oh",
    "セレビィ": "Celebi",
    # Popular newer ones
    "キモリ": "Treecko",
    "アチャモ": "Torchic",
    "ミズゴロウ": "Mudkip",
    "ラルトス": "Ralts",
    "サーナイト": "Gardevoir",
    "エルレイド": "Gallade",
    "クチート": "Mawile",
    "ボスゴドラ": "Aggron",
    "フライゴン": "Flygon",
    "チルタリス": "Altaria",
    "ミロカロス": "Milotic",
    "カクレオン": "Keckleon",
    "ジュペッタ": "Banette",
    "アブソル": "Absol",
    "タツベイ": "Bagon",
    "ボーマンダ": "Salamence",
    "ダンバル": "Beldum",
    "メタグロス": "Metagross",
    "レジロック": "Regirock",
    "レジアイス": "Regice",
    "レジスチル": "Registeel",
    "ラティアス": "Latias",
    "ラティオス": "Latios",
    "カイオーガ": "Kyogre",
    "グラードン": "Groudon",
    "レックウザ": "Rayquaza",
    "ジラーチ": "Jirachi",
    "デオキシス": "Deoxys",
    "ナエトル": "Turtwig",
    "ヒコザル": "Chimchar",
    "ポッチャマ": "Piplup",
    "レントラー": "Luxray",
    "ガブリアス": "Garchomp",
    "ルカリオ": "Lucario",
    "ディアルガ": "Dialga",
    "パルキア": "Palkia",
    "ギラティナ": "Giratina",
    "クレセリア": "Cresselia",
    "ダークライ": "Darkrai",
    "アルセウス": "Arceus",
    "ビクティニ": "Victini",
    "ツタージャ": "Snivy",
    "ポカブ": "Tepig",
    "ミジュマル": "Oshawott",
    "ゾロアーク": "Zoroark",
    "ゼクロム": "Zekrom",
    "レシラム": "Reshiram",
    "キュレム": "Kyurem",
    "ハリマロン": "Chespin",
    "フォッコ": "Fennekin",
    "ケロマツ": "Froakie",
    "ゲッコウガ": "Greninja",
    "ゼルネアス": "Xerneas",
    "イベルタル": "Yveltal",
    "ジガルデ": "Zygarde",
    "モクロー": "Rowlet",
    "ニャビー": "Litten",
    "アシマリ": "Popplio",
    "ミミッキュ": "Mimikyu",
    "カプ・コケコ": "Tapu Koko",
    "ソルガレオ": "Solgaleo",
    "ルナアーラ": "Lunala",
    "サルノリ": "Grookey",
    "ヒバニー": "Scorbunny",
    "メッソン": "Sobble",
    "ザシアン": "Zacian",
    "ザマゼンタ": "Zamazenta",
    "ムゲンダイナ": "Eternatus",
    "ニャオハ": "Sprigatito",
    "ホゲータ": "Fuecoco",
    "クワッス": "Quaxly",
    "コライドン": "Koraidon",
    "ミライドン": "Miraidon",
    # Additional Generation 3
    "ジュプトル": "Grovyle",
    "ジュカイン": "Sceptile",
    "ワカシャモ": "Combusken",
    "バシャーモ": "Blaziken",
    "ヌマクロー": "Marshtomp",
    "ラグラージ": "Swampert",
    "ポチエナ": "Poochyena",
    "グラエナ": "Mightyena",
    "ジグザグマ": "Zigzagoon",
    "マッスグマ": "Linoone",
    "ケムッソ": "Wurmple",
    "カラサリス": "Silcoon",
    "アゲハント": "Beautifly",
    "マゆルド": "Cascoon",
    "ドクケイル": "Dustox",
    "ハスボー": "Lotad",
    "ハスブレロ": "Lombre",
    "ルンパッパ": "Ludicolo",
    "タネボー": "Seedot",
    "コノハナ": "Nuzleaf",
    "ダーテング": "Shiftry",
    "スバメ": "Taillow",
    "オオスバメ": "Swellow",
    "キャモメ": "Wingull",
    "ペリッパー": "Pelipper",
    "キルリア": "Kirlia",
    "アメタマ": "Surskit",
    "アメモース": "Masquerain",
    "キノココ": "Shroomish",
    "キノガッサ": "Breloom",
    "ナマケロ": "Slakoth",
    "ヤルキモノ": "Vigoroth",
    "ケッキング": "Slaking",
    "ツチニン": "Nincada",
    "テッカニン": "Ninjask",
    "ヌケニン": "Shedinja",
    "ゴニョニョ": "Whismur",
    "ドゴーム": "Loudred",
    "バクオング": "Exploud",
    "マクノシタ": "Makuhita",
    "ハリテヤマ": "Hariyama",
    "ルリリ": "Azurill",
    "ノズパス": "Nosepass",
    "エネコ": "Skitty",
    "エネコロロ": "Delcatty",
    "ヤミラミ": "Sableye",
    "ココドラ": "Aron",
    "コドラ": "Lairon",
    "アサナン": "Meditite",
    "チャーレム": "Medicham",
    "ラクライ": "Electrike",
    "ライボルト": "Manectric",
    "プラスル": "Plusle",
    "マイナン": "Minun",
    "バルビート": "Volbeat",
    "イルミーゼ": "Illumise",
    "ロゼリア": "Roselia",
    "ゴクリン": "Gulpin",
    "マルノーム": "Swalot",
    "キバニア": "Carvanha",
    "サメハダー": "Sharpedo",
    "ホエルコ": "Wailmer",
    "ホエルオー": "Wailord",
    "ドンメル": "Numel",
    "バクーダ": "Camerupt",
    "コータス": "Torkoal",
    "バネブー": "Spoink",
    "ブーピッグ": "Grumpig",
    "パッチール": "Spinda",
    "ナックラー": "Trapinch",
    "ビブラーバ": "Vibrava",
    "サボネア": "Cacnea",
    "ノクタス": "Cacturne",
    "チルット": "Swablu",
    "ザングース": "Zangoose",
    "ハブネーク": "Seviper",
    "ルナトーン": "Lunatone",
    "ソルロック": "Solrock",
    "ドジョッチ": "Barboach",
    "ナマズン": "Whiscash",
    "ヘイガニ": "Corphish",
    "シザリガー": "Crawdaunt",
    "ヤジロン": "Baltoy",
    "ネンドール": "Claydol",
    "リリーラ": "Lileep",
    "ユレイドル": "Cradily",
    "アノプス": "Anorith",
    "アーマルド": "Armaldo",
    "ヒンバス": "Feebas",
    "ポワルン": "Castform",
    "カクレオン": "Keckleon",
    "カゲボウズ": "Shuppet",
    "ヨマワル": "Duskull",
    "サマヨール": "Dusclops",
    "トロピウス": "Tropius",
    "チリーン": "Chimecho",
    "ユキワラシ": "Snorunt",
    "オニゴーリ": "Glalie",
    "タマザラシ": "Spheal",
    "トドグラー": "Sealeo",
    "トドゼルガ": "Walrein",
    "パールル": "Clamperl",
    "ハンテール": "Huntail",
    "サクラビス": "Gorebyss",
    "ジーランス": "Relicanth",
    "ラブカス": "Luvdisc",
    "コモルー": "Shelgon",
    "コモルー": "Shelgon",
    "コモルー": "Shelgon",
    "メタング": "Metang",
    # Additional Gen 4
    "ハヤシガメ": "Grotle",
    "ドダイトス": "Torterra",
    "モウカザル": "Monferno",
    "ゴウカザル": "Infernape",
    "ポッタイシ": "Prinplup",
    "エンペルト": "Empoleon",
    "ムックル": "Starly",
    "ムクバード": "Staravia",
    "ムクホーク": "Staraptor",
    "ビッパ": "Bidoof",
    "ビーダル": "Bibarel",
    "コロボーシ": "Kricketot",
    "コロトック": "Kricketune",
    "コリンク": "Shinx",
    "ルクシオ": "Luxio",
    "スボミー": "Budew",
    "ロズレイド": "Roserade",
    "ズガイドス": "Cranidos",
    "ラムパルド": "Rampardos",
    "タテトプス": "Shieldon",
    "トリデプス": "Bastiodon",
    "ミノムッチ": "Burmy",
    "ミノマダム": "Wormadam",
    "ガーメイル": "Mothim",
    "ミツハニー": "Combee",
    "ビークイン": "Vespiquen",
    "パチリス": "Pachirisu",
    "ブイゼル": "Buizel",
    "フローゼル": "Floatzel",
    "チェリンボ": "Cherubi",
    "チェリム": "Cherrim",
    "カラナクシ": "Shellos",
    "トリトドン": "Gastrodon",
    "エテボース": "Ambipom",
    "フワンテ": "Drifloon",
    "フワライド": "Drifblim",
    "ミミロル": "Buneary",
    "ミミロップ": "Lopunny",
    "ムウマージ": "Mismagius",
    "ドンカラス": "Honchkrow",
    "ニャルマー": "Glameow",
    "ブニャット": "Purugly",
    "リーシャン": "Chingling",
    "スカンプー": "Stunky",
    "スカタンク": "Skuntank",
    "ドーミラー": "Bronzor",
    "ドータクン": "Bronzong",
    "ウソハチ": "Bonsly",
    "マネネ": "Mime Jr.",
    "ピンプク": "Happiny",
    "ペラップ": "Chatot",
    "ミカルゲ": "Spiritomb",
    "フカマル": "Gible",
    "ガバイト": "Gabite",
    "ゴンベ": "Munchlax",
    "リオル": "Riolu",
    "ヒポポタス": "Hippopotas",
    "カバルドン": "Hippowdon",
    "スコルピ": "Skorupi",
    "ドラピオン": "Drapion",
    "グレッグル": "Croagunk",
    "ドクロッグ": "Toxicroak",
    "マスキッパ": "Carnivine",
    "ケイコウオ": "Finneon",
    "ネオラント": "Lumineon",
    "タマンタ": "Mantyke",
    "ユキカブリ": "Snover",
    "ユキノオー": "Abomasnow",
    "マニューラ": "Weavile",
    "ジバコイル": "Magnezone",
    "ベロベルト": "Lickilicky",
    "ドサイドン": "Rhyperior",
    "モジャンボ": "Tangrowth",
    "エレキブル": "Electivire",
    "ブーバーン": "Magmortar",
    "トゲキッス": "Togekiss",
    "メガヤンマ": "Yanmega",
    "リーフィア": "Leafeon",
    "グレイシア": "Glaceon",
    "グライオン": "Gliscor",
    "マンムー": "Mamoswine",
    "ポリゴンZ": "Porygon-Z",
    "ダイノーズ": "Probopass",
    "ヨノワール": "Dusknoir",
    "ユキメノコ": "Froslass",
    "ロトム": "Rotom",
    "ユクシー": "Uxie",
    "エムリット": "Mesprit",
    "アグノム": "Azelf",
    "マナフィ": "Manaphy",
    "シェイミ": "Shaymin",
    # Additional Gen 5
    "ジャノビー": "Servine",
    "ジャローダ": "Serperior",
    "チャオブー": "Pignite",
    "エンブオー": "Emboar",
    "フタチマル": "Dewott",
    "ダイケンキ": "Samurott",
    "ミネズミ": "Patrat",
    "ミルホッグ": "Watchog",
    "ヨーテリー": "Lilipup",
    "ハーデリア": "Herdier",
    "ムーランド": "Stoutland",
    "チョロネコ": "Purrloin",
    "レパルダス": "Liepard",
    "ヤナップ": "Pansage",
    "ヤナッキー": "Simisage",
    "バオップ": "Pansear",
    "バオッキー": "Simisear",
    "ヒヤップ": "Panpour",
    "ヒヤッキー": "Simipour",
    "ムナッパ": "Munna",
    "ムシャーナ": "Musharna",
    "マメパト": "Pidove",
    "ハトーボー": "Tranquill",
    "ケンホロウ": "Unfezant",
    "シママ": "Blitzle",
    "ゼブライカ": "Zebstrika",
    "ダンゴロ": "Roggenrola",
    "ガントル": "Boldore",
    "ギガイアス": "Gigalith",
    "コロモリ": "Woobat",
    "ココロモリ": "Swoobat",
    "モグリュー": "Drilbur",
    "ドリュウズ": "Excadrill",
    "タブンネ": "Audino",
    "ドッコラー": "Timburr",
    "ドテッコツ": "Gurdurr",
    "ローブシン": "Conkeldurr",
    "オタマロ": "Tympole",
    "ガマガル": "Palpitoad",
    "ガマゲロゲ": "Seismitoad",
    "ナゲキ": "Throh",
    "ダゲキ": "Sawk",
    "クルミル": "Sewaddle",
    "クルマユ": "Swadloon",
    "ハハコモリ": "Leavanny",
    "フシデ": "Venipede",
    "ホイーガ": "Whirlipede",
    "ペンドラー": "Scolipede",
    "モンメン": "Cottonee",
    "エルフーン": "Whimsicott",
    "チュリネ": "Petilil",
    "ドレディア": "Lilligant",
    "バスラオ": "Basculin",
    "メグロコ": "Sandile",
    "ワルビル": "Krokorok",
    "ワルビアル": "Krookodile",
    "ダルマッカ": "Darumaka",
    "ヒヒダルマ": "Darmanitan",
    "マラカッチ": "Maractus",
    "イシズマイ": "Dwebble",
    "イワパレス": "Crustle",
    "ズルッグ": "Scraggy",
    "ズルズキン": "Scrafty",
    "シンボラー": "Sigilyph",
    "デスマス": "Yamask",
    "デスカーン": "Cofagrigus",
    "プロトーガ": "Tirtouga",
    "アバゴーラ": "Carracosta",
    "アーケン": "Archen",
    "アーケオス": "Archeops",
    "ヤブクロン": "Trubbish",
    "ダストダス": "Garbodor",
    "ゾロア": "Zorua",
    "チラーミィ": "Minccino",
    "チラチーノ": "Cinccino",
    "ゴチム": "Gothita",
    "ゴチミル": "Gothorita",
    "ゴチルゼル": "Gothitelle",
    "ユニラン": "Solosis",
    "ダブラン": "Duosion",
    "ランクルス": "Reuniclus",
    "コアルヒー": "Ducklett",
    "スワンナ": "Swanna",
    "バニプッチ": "Vanillite",
    "バニリッチ": "Vanillish",
    "バイバニラ": "Vanilluxe",
    "シキジカ": "Deerling",
    "メブキジカ": "Sawsbuck",
    "エモンガ": "Emolga",
    "カブルモ": "Karrablast",
    "シュバルゴ": "Escavalier",
    "タマゲタケ": "Foongus",
    "モロバレル": "Amoonguss",
    "プルリル": "Frillish",
    "ブルンゲル": "Jellicent",
    "ママンボウ": "Alomomola",
    "バチュル": "Joltik",
    "デンチュラ": "Galvantula",
    "テッシード": "Ferroseed",
    "ナットレイ": "Ferrothorn",
    "ギアル": "Klink",
    "ギギアル": "Klang",
    "ギギギアル": "Klinklang",
    "シビシラス": "Tynamo",
    "シビビール": "Eelektrik",
    "シビルドン": "Eelektross",
    "リグレー": "Elgyem",
    "オーベム": "Beheeyem",
    "ヒトモシ": "Litwick",
    "ランプラー": "Lampent",
    "シャンデラ": "Chandelure",
    "キバゴ": "Axew",
    "オノンド": "Fraxure",
    "オノノクス": "Haxorus",
    "クマシュン": "Cubchoo",
    "ツンベアー": "Beartic",
    "フリージオ": "Cryogonal",
    "チョボマキ": "Shelmet",
    "アギルダー": "Accelgor",
    "マッギョ": "Stunfisk",
    "コジョフー": "Mienfoo",
    "コジョンド": "Mienshao",
    "クリムガン": "Druddigon",
    "ゴビット": "Golett",
    "ゴルーグ": "Golurk",
    "コマタナ": "Pawniard",
    "キリキザン": "Bisharp",
    "バッフロン": "Bouffalant",
    "ワシボン": "Rufflet",
    "ウォーグル": "Braviary",
    "バルチャイ": "Vullaby",
    "バルジーナ": "Mandibuzz",
    "クイタラン": "Heatmor",
    "アイアント": "Durant",
    "モノズ": "Deino",
    "ジヘッド": "Zweilous",
    "サザンドラ": "Hydreigon",
    "メラルバ": "Larvesta",
    "ウルガモス": "Volcarona",
    "コバルオン": "Cobalion",
    "テラキオン": "Terrakion",
    "ビリジオン": "Virizion",
    "トルネロス": "Tornadus",
    "ボルトロス": "Thundurus",
    "ランドロス": "Landorus",
    "メロエッタ": "Meloetta",
    "ゲノセクト": "Genesect",
    # Additional Gen 6
    "ハリボーグ": "Quilladin",
    "ブリガロン": "Chesnaught",
    "テールナー": "Braixen",
    "マフォクシー": "Delphox",
    "ゲコガシラ": "Frogadier",
    "ホルビー": "Bunnelby",
    "ホルード": "Diggersby",
    "ヤヤコマ": "Fletchling",
    "ヒノヤコマ": "Fletchinder",
    "ファイアロー": "Talonflame",
    "コフキムシ": "Scatterbug",
    "コフーライ": "Spewpa",
    "ビビヨン": "Vivillon",
    "シシコ": "Litleo",
    "カエンジシ": "Pyroar",
    "フラベベ": "Flabébé",
    "フラエッテ": "Floette",
    "フラージェス": "Florges",
    "メェーメェー": "Skiddo",
    "ゴーゴート": "Gogoat",
    "ヤンチャム": "Pancham",
    "ゴロンダ": "Pangoro",
    "トリミアン": "Furfrou",
    "ニャスパー": "Espurr",
    "ニャオニクス": "Meowstic",
    "ヒトツキ": "Honedge",
    "ニダンギル": "Doublade",
    "ギルガルド": "Aegislash",
    "シュシュプ": "Spritzee",
    "フレフワン": "Aromatisse",
    "ペロッパフ": "Swirlix",
    "ペロリーム": "Slurpuff",
    "マーイーカ": "Inkay",
    "カラマネロ": "Malamar",
    "カメテテ": "Binacle",
    "ガメノデス": "Barbaracle",
    "クズモー": "Skrelp",
    "ドラミドロ": "Dragalge",
    "ウデッポウ": "Clauncher",
    "ブロスター": "Clawitzer",
    "エリキテル": "Helioptile",
    "エレザード": "Heliolisk",
    "チゴラス": "Tyrunt",
    "ガチゴラス": "Tyrantrum",
    "アマルス": "Amaura",
    "アマルルガ": "Aurorus",
    "ニンフィア": "Sylveon",
    "ルチャブル": "Hawlucha",
    "デデンネ": "Dedenne",
    "メレシー": "Carbink",
    "ヌメラ": "Goomy",
    "ヌメイル": "Sliggoo",
    "ヌメルゴン": "Goodra",
    "クレッフィ": "Klefki",
    "ボクレー": "Phantump",
    "オーロット": "Trevenant",
    "バケッチャ": "Pumpkaboo",
    "パンプジン": "Gourgeist",
    "カチコール": "Bergmite",
    "クレベース": "Avalugg",
    "オンバット": "Noibat",
    "オンバーン": "Noivern",
    "ディアンシー": "Diancie",
    "フーパ": "Hoopa",
    "ボルケニオン": "Volcanion",
}

# TCG Suffixes and Prefixes
PREFIXES = {
    "メガ": "Mega ",
    "ゲンシ": "Primal ",
    "アローラの": "Alolan ",
    "ガラルの": "Galarian ",
    "ヒスイの": "Hisuian ",
    "パルデアの": "Paldean ",
    "かがやく": "Radiant ",
}

SUFFIXES = {
    "V": " V",
    "VMAX": " VMAX",
    "VSTAR": " VSTAR",
    "ex": " ex",
    "EX": " EX",
    "GX": " GX",
    "BREAK": " BREAK",
    "LEGEND": " LEGEND",
    "LV.X": " LV.X",
    " X": " X",
    " Y": " Y",
    "X": " X",
    "Y": " Y",
    "たね": "", # Basic
    "1撃": "Single Strike",
    "連撃": "Rapid Strike",
    "一撃": "Single Strike",
}

def translate_pokemon_name(name_ja: str) -> str:
    if not name_ja:
        return name_ja
        
    # Check direct match first
    if name_ja in POKEMON_NAME_MAP:
        return POKEMON_NAME_MAP[name_ja]
        
    translated_name = name_ja
    prefix_str = ""
    suffix_str = ""
    
    # Handle prefixes
    for jp_prefix, en_prefix in PREFIXES.items():
        if translated_name.startswith(jp_prefix):
            prefix_str = en_prefix
            translated_name = translated_name[len(jp_prefix):]
            break
            
    # Handle suffixes
    # Sort suffixes by length descending to match longest first (e.g., VSTAR before V)
    sorted_suffixes = sorted(SUFFIXES.items(), key=lambda x: len(x[0]), reverse=True)
    for jp_suffix, en_suffix in sorted_suffixes:
        if translated_name.endswith(jp_suffix):
            suffix_str = en_suffix
            translated_name = translated_name[:-len(jp_suffix)]
            break
            
    # Clean up any remaining whitespace or special chars
    translated_name = translated_name.strip()
    
    # Try looking up the base name
    if translated_name in POKEMON_NAME_MAP:
        return f"{prefix_str}{POKEMON_NAME_MAP[translated_name]}{suffix_str}"
        
    # If not found, return the original or partially translated if we had prefix/suffix
    if prefix_str or suffix_str:
        # If we found a prefix/suffix but not the base name, 
        # it might be a Pokemon not in our list or something else.
        # We'll return None to fallback to Japanese as requested.
        return None
        
    return None
